name: Perf+ Kernel Builder

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Choose branch'
        required: true
        default: 'lineage-23.2'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone Kernel Source
        run: |
          git clone https://github.com/veedz/kernel_xiaomi_sm8250 -b ${{ github.event.inputs.branch }} ${{ github.workspace }}/kernel_xiaomi_sm8250 --depth=1

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: /home/runner/.ccache
          key: ${{ runner.os }}-ccache-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ github.ref_name }}-

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bc bison gcc gcc-aarch64-linux-gnu ccache p7zip-full lld cpio python-is-python3 zstd wget curl

      - name: Build Kernel
        run: |
          cd kernel_xiaomi_sm8250
          git submodule update --init
          bash build.sh
        env:
          TGTOKEN: ${{ secrets.TGTOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          